/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    "createRule": null,
    "deleteRule": null,
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text982552870",
        "max": 0,
        "min": 0,
        "name": "nombre",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "select1309676077",
        "maxSelect": 1,
        "name": "categoria",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "Abarrotes",
          "Accesorios",
          "Agencia de viajes",
          "Antojitos",
          "Barbería",
          "Boutique",
          "Cafetería",
          "Carnicería",
          "Cerrajería",
          "Ciber",
          "Consultorio médico",
          "Dulcería",
          "Estética",
          "Farmacia",
          "Ferretería",
          "Florería",
          "verdulería",
          "Heladería",
          "Imprenta",
          "Joyería",
          "Lavandería",
          "Lonchería",
          "Papelería",
          "Panadería",
          "Pastelería",
          "Peluquería",
          "Pescadería",
          "Pollería",
          "Refaccionaria",
          "Restaurante",
          "Taquería",
          "Taller mecánico",
          "Taller de costura",
          "Tienda de ropa",
          "Tienda de electrónicos",
          "Tortillería",
          "Veterinaria",
          "Zapatería"
        ]
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text2687119104",
        "max": 0,
        "min": 0,
        "name": "descripcion",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text4085563029",
        "max": 0,
        "min": 0,
        "name": "direccion",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3253144191",
        "max": 0,
        "min": 0,
        "name": "telefono",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text4222712125",
        "max": 0,
        "min": 0,
        "name": "whatsapp",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3797439395",
        "max": 0,
        "min": 0,
        "name": "horario",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "file3834550803",
        "maxSelect": 1,
        "maxSize": 0,
        "mimeTypes": [],
        "name": "logo",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "hidden": false,
        "id": "file929718273",
        "maxSelect": 1,
        "maxSize": 0,
        "mimeTypes": [],
        "name": "imagenes",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "hidden": false,
        "id": "file882009953",
        "maxSelect": 1,
        "maxSize": 0,
        "mimeTypes": [],
        "name": "fecha_afiliacion",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "hidden": false,
        "id": "bool2882213148",
        "name": "activo",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "hidden": false,
        "id": "number3777548247",
        "max": null,
        "min": null,
        "name": "orden",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "id": "pbc_1928099433",
    "indexes": [],
    "listRule": null,
    "name": "negocios",
    "system": false,
    "type": "base",
    "updateRule": null,
    "viewRule": null
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_1928099433");

  return app.delete(collection);
})
