/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    "createRule": "@request.auth.id != \"\"",
    "deleteRule": null,
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "hidden": false,
        "id": "relation2777886149",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "clienteId",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_2604406982",
        "hidden": false,
        "id": "relation3748578879",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "vendedorId",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_4092854851",
        "hidden": false,
        "id": "relation4100695912",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "productoId",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "hidden": false,
        "id": "select1882004807",
        "maxSelect": 1,
        "name": "tipo",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "contado",
          "credito"
        ]
      },
      {
        "hidden": false,
        "id": "select643686883",
        "maxSelect": 1,
        "name": "estado",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "pendiente_vendedor",
          "vendedor_validado",
          "admin_validado",
          "completada",
          "cancelada"
        ]
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text4146295014",
        "max": 0,
        "min": 0,
        "name": "productoNombre",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "number3675922530",
        "max": null,
        "min": null,
        "name": "productoPrecio",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number2526520864",
        "max": null,
        "min": null,
        "name": "enganche",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "bool195311921",
        "name": "enganchePagado",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_2604406982",
        "hidden": false,
        "id": "relation3219588930",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "engancheRecibidoPor",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "hidden": false,
        "id": "file396029532",
        "maxSelect": 1,
        "maxSize": 0,
        "mimeTypes": [],
        "name": "engancheRecibidoFecha",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "hidden": false,
        "id": "number1222512077",
        "max": null,
        "min": null,
        "name": "pagoSemanal",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number3835477567",
        "max": null,
        "min": null,
        "name": "semanasTotales",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number2770866498",
        "max": null,
        "min": null,
        "name": "ultimoPago",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number3521371141",
        "max": null,
        "min": null,
        "name": "totalPagar",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "bool3189150916",
        "name": "incluyeTanda",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_2482852971",
        "hidden": false,
        "id": "relation4141133531",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "tandaId",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text2053536070",
        "max": 0,
        "min": 0,
        "name": "tandaNombre",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1087294152",
        "max": 0,
        "min": 0,
        "name": "tandaPosicion",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1608502757",
        "max": 0,
        "min": 0,
        "name": "tandaCuota",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_379312381",
        "hidden": false,
        "id": "relation2373033017",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "tandaRondas",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "hidden": false,
        "id": "number237877819",
        "max": null,
        "min": null,
        "name": "pagosRealizados",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "json1155799219",
        "maxSize": 0,
        "name": "historialPagos",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "json"
      },
      {
        "hidden": false,
        "id": "file3484194835",
        "maxSelect": 1,
        "maxSize": 0,
        "mimeTypes": [],
        "name": "fechaSolicitud",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "hidden": false,
        "id": "file3463112278",
        "maxSelect": 1,
        "maxSize": 0,
        "mimeTypes": [],
        "name": "fechaValidacionVendedor",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "hidden": false,
        "id": "file3605631128",
        "maxSelect": 1,
        "maxSize": 0,
        "mimeTypes": [],
        "name": "fechaValidacionAdmin",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text328529707",
        "max": 0,
        "min": 0,
        "name": "notasVendedor",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text2835243259",
        "max": 0,
        "min": 0,
        "name": "notasAdmin",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "json1365586463",
        "maxSize": 0,
        "name": "clienteDataSnapshot",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "json"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "id": "pbc_4075287140",
    "indexes": [],
    "listRule": "@request.auth.rol = \"admin\" || (vendedorId = @request.auth.id)",
    "name": "solicitudes",
    "system": false,
    "type": "base",
    "updateRule": "@request.auth.rol = \"admin\" || (vendedorId = @request.auth.id && estado = \"pendiente_vendedor\")",
    "viewRule": "@request.auth.rol = \"admin\" || (vendedorId = @request.auth.id)"
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_4075287140");

  return app.delete(collection);
})
