/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    "createRule": "@request.auth.role = \"admin\"",
    "deleteRule": "@request.auth.role = \"admin\"",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "hidden": false,
        "id": "relation1689669068",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "userId",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "hidden": false,
        "id": "number2868650187",
        "max": null,
        "min": null,
        "name": "nivel",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number777123888",
        "max": null,
        "min": null,
        "name": "productosComprados",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number2386483518",
        "max": null,
        "min": null,
        "name": "productosPagados",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number1265192798",
        "max": null,
        "min": null,
        "name": "productosEnCurso",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number3942894169",
        "max": null,
        "min": null,
        "name": "deudaActual",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number4139286901",
        "max": null,
        "min": null,
        "name": "limiteDeuda",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number1585730330",
        "max": null,
        "min": null,
        "name": "trustScore",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "select1356056661",
        "maxSelect": 1,
        "name": "estadoKyc",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "pendiente",
          "aprobado",
          "rechazado"
        ]
      },
      {
        "hidden": false,
        "id": "bool1348538761",
        "name": "documentosCompletos",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text308409472",
        "max": 0,
        "min": 0,
        "name": "tarjetaId",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "number3235478179",
        "max": null,
        "min": null,
        "name": "numeroTarjeta",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1706581865",
        "max": 0,
        "min": 0,
        "name": "codigoColonia",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3528480305",
        "max": 0,
        "min": 0,
        "name": "direccionCalle",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3306371528",
        "max": 0,
        "min": 0,
        "name": "direccionNumero",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text249137942",
        "max": 0,
        "min": 0,
        "name": "direccionInterior",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text2951517059",
        "max": 0,
        "min": 0,
        "name": "direccionColonia",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3494384113",
        "max": 0,
        "min": 0,
        "name": "direccionMunicipio",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3201293768",
        "max": 0,
        "min": 0,
        "name": "direccionCiudad",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text370424245",
        "max": 0,
        "min": 0,
        "name": "direccionEstado",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3932646485",
        "max": 0,
        "min": 0,
        "name": "direccionCp",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1735961695",
        "max": 0,
        "min": 0,
        "name": "direccionReferencias",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "json4092298133",
        "maxSize": 0,
        "name": "ubicacionGPS",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "json"
      },
      {
        "hidden": false,
        "id": "select479566075",
        "maxSelect": 1,
        "name": "diaPago",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "lunes",
          "martes"
        ]
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text4195722820",
        "max": 0,
        "min": 0,
        "name": "telefonoAlternativo",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "bool1233992686",
        "name": "datosCompletos",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "hidden": false,
        "id": "bool2308821219",
        "name": "aceptaTerminos",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "hidden": false,
        "id": "date734240834",
        "max": "",
        "min": "",
        "name": "fechaAceptaTerminos",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "hidden": false,
        "id": "date3220005127",
        "max": "",
        "min": "",
        "name": "fechaPrimerProducto",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "hidden": false,
        "id": "date429514562",
        "max": "",
        "min": "",
        "name": "fechaUltimoProducto",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "hidden": false,
        "id": "date2956787380",
        "max": "",
        "min": "",
        "name": "fechaPrimerCompra",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "hidden": false,
        "id": "date3131829448",
        "max": "",
        "min": "",
        "name": "fechaUltimoPago",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "hidden": false,
        "id": "date3731923163",
        "max": "",
        "min": "",
        "name": "fechaUltimaCompra",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "hidden": false,
        "id": "number568939082",
        "max": null,
        "min": null,
        "name": "totalGastado",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "id": "pbc_2442875294",
    "indexes": [],
    "listRule": "@request.auth.role = \"admin\"",
    "name": "clients",
    "system": false,
    "type": "base",
    "updateRule": "userId = @request.auth.id || @request.auth.role = \"admin\"",
    "viewRule": "userId = @request.auth.id || @request.auth.role = \"admin\""
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_2442875294");

  return app.delete(collection);
})
