/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    "createRule": "@request.auth.id != \"\"",
    "deleteRule": "@request.auth.id = usuarioId || @request.auth.role = \"admin\"",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text982552870",
        "max": 0,
        "min": 0,
        "name": "nombre",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text2687119104",
        "max": 0,
        "min": 0,
        "name": "descripcion",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "select1309676077",
        "maxSelect": 1,
        "name": "categoria",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "Blazers",
          "Camisas",
          "Playeras",
          "Pantalones",
          "Jeans",
          "Vestidos",
          "Faldas",
          "Sudaderas",
          "Chamarras",
          "Abrigos",
          "Suéteres",
          "Shorts",
          "Accesorios",
          "Calzado",
          "Bolsos",
          "Otro"
        ]
      },
      {
        "hidden": false,
        "id": "select3665803540",
        "maxSelect": 1,
        "name": "subcategoria",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "Casual",
          "Formal",
          "Deportivo",
          "Fiesta",
          "Oficina",
          "Playa",
          "Invierno",
          "Verano",
          "Otro"
        ]
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1718304072",
        "max": 0,
        "min": 0,
        "name": "coleccion",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "select4225394261",
        "maxSelect": 1,
        "name": "talla",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "XS",
          "S",
          "M",
          "L",
          "XL",
          "XXL",
          "Única"
        ]
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1716930793",
        "max": 0,
        "min": 0,
        "name": "color",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text2092856725",
        "max": 0,
        "min": 0,
        "name": "material",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "select2684389434",
        "maxSelect": 1,
        "name": "genero",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "Mujer",
          "Hombre",
          "Unisex",
          "Niños"
        ]
      },
      {
        "hidden": false,
        "id": "number380223906",
        "max": null,
        "min": null,
        "name": "precio",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number319960130",
        "max": null,
        "min": null,
        "name": "precioAnterior",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number2557365855",
        "max": null,
        "min": null,
        "name": "precioCredito",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number2526520864",
        "max": null,
        "min": null,
        "name": "enganche",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number1222512077",
        "max": null,
        "min": null,
        "name": "pagoSemanal",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number1261852256",
        "max": null,
        "min": null,
        "name": "stock",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text261109956",
        "max": 0,
        "min": 0,
        "name": "sku",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "file2199507635",
        "maxSelect": 1,
        "maxSize": 0,
        "mimeTypes": [],
        "name": "imagen",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "hidden": false,
        "id": "file929718273",
        "maxSelect": 99,
        "maxSize": 0,
        "mimeTypes": [],
        "name": "imagenes",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "hidden": false,
        "id": "json16035862",
        "maxSize": 0,
        "name": "tallas",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "json"
      },
      {
        "hidden": false,
        "id": "json1743014602",
        "maxSize": 0,
        "name": "colores",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "json"
      },
      {
        "hidden": false,
        "id": "json3715058207",
        "maxSize": 0,
        "name": "etiquetas",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "json"
      },
      {
        "hidden": false,
        "id": "select2590760637",
        "maxSelect": 1,
        "name": "temporada",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "Primavera-Verano",
          "Otoño-Invierno",
          "Todo el año"
        ]
      },
      {
        "hidden": false,
        "id": "bool2882213148",
        "name": "activo",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "hidden": false,
        "id": "bool1454753261",
        "name": "nuevo",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "hidden": false,
        "id": "bool720804565",
        "name": "destacado",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "hidden": false,
        "id": "bool2891810072",
        "name": "edicionLimitada",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "hidden": false,
        "id": "number3777548247",
        "max": null,
        "min": null,
        "name": "orden",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number593624199",
        "max": null,
        "min": null,
        "name": "visitas",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number2319118872",
        "max": null,
        "min": null,
        "name": "calificacion",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number3841207618",
        "max": null,
        "min": null,
        "name": "totalComentarios",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "hidden": false,
        "id": "relation4006211842",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "usuarioId",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "id": "pbc_3655375820",
    "indexes": [],
    "listRule": "activo = true",
    "name": "eshe_parallel",
    "system": false,
    "type": "base",
    "updateRule": "@request.auth.id = usuarioId || @request.auth.role = \"admin\"",
    "viewRule": null
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_3655375820");

  return app.delete(collection);
})
